version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/public/:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      backend:
        condition: service_started

  backend:
    build: .
    depends_on:
      db:
        condition: service_healthy
      redis1:
        condition: service_started
      redis2:
        condition: service_started

  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      - POSTGRES_USER=editor
      - POSTGRES_PASSWORD=xVfp9KzAR5F6qjLhd7Z8Ct
      - POSTGRES_DB=editor
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U editor -d editor"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis1:
    image: redis:7-alpine
    container_name: redis1
    command: redis-server
    volumes:
      - redis_data1:/data

  redis2:
    image: redis:7-alpine
    container_name: redis2
    command: redis-server
    volumes:
      - redis_data2:/data

volumes:
  postgres_data:
  redis_data1:
  redis_data2:
